- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendareventlistmodel.cpp
- src/calendareventlistmodel.h
Modify a bit the event list model, so the identifiers that are the input of the model are also expose as data for each row in the model.
@chriadam , you can see the use for it in https://github.com/dcaliste/harbour/logbook
> [nemo-qml-plugin-calendar] Expose identifier in event list model.

- src/calendarmanager.cpp
- src/calendarworker.cpp
- tests/tests.pro
- tests/tst_calendaragendamodel/tst_calendaragendamodel.cpp
- tests/tst_calendaragendamodel/tst_calendaragendamodel.pro
It's actually the same PR than #11 but I was working on it also based on a new test to ensure that we're not creating regressions, or at least trying to be confident not to !
The test is demonstrating the problem : an event hapenning on D day in Ho Chi Minh city at 3am should be in an AgendaModel featuring D-1 day if this agenda model is created in a Paris time zone.
Creating such test, I actually also found that the AgendaModel is broken for multi-day agendas ! (luckily we're using it only for single day ranges in the calendar application). The `QHash::unite()` has been found to be misleading because uniting a hash with another one that contains the same keys result in the first hash to contains several time the key. Which kind of defeat the initial purpose of a Hash instead of a …
> Fix missing events from different tz in agenda model.

- src/calendardata.h
- src/calendarevent.cpp
- src/calendarevent.h
- src/calendarmanager.cpp
- src/calendarutils.cpp
- src/calendarutils.h
- src/calendarworker.cpp
- src/calendarworker.h
It is exposing the STATUS property to QML, but it requires a patch in KCalendarCore that is not yet there, since KCalendarCore is currently hiding cancelled occurrences of recurring events.
It can be tested with plain cancelled events though.
> [nemo-qml-plugin-calendar] Expose the event status to QML.

- tests/tests.xml
- tests/tst_calendarmanager/tst_calendarmanager.cpp
Bunch of things were going wrong here:
- The test was creating its own instance of CalendarManager to test,
used in the range test, but then the api test used the singleton
instance -> two calendar manager instances running at the same time,
other being deleted before the direct mkcal instances. Confusion.
Now just creating a new instance for each test, making the tests mess up
less with each other.
- Notebook api test failing got the test crashing if it hadn't yet
instantiated mStorage. Added null protection
- Notebook api is adjusting the default notebook on and off, but
at the same time expecting the test is started with a default notebook
set. Thus based on luck the test started failing if executed on an
existing database. Removed the signal spy on loading and now checking
only the …
> [nemo-qml-plugin-calendar] Fix calendarmanager test. JB#57290

- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendarmanager.cpp
- src/calendarmanager.h
- src/calendarutils.cpp
- src/calendarworker.cpp
- src/calendarworker.h
- tests/tst_calendarevent/tst_calendarevent.cpp
- tests/tst_calendarmanager/tst_calendarmanager.cpp
The follow-up PR from sailfishos/mkcal#17 implementing the `storageUpdated` signal.
Basically, the major change is that when this signal is received, we're not flushing loaded ranges and notebooks, so on next `loadData()` call from the manager, we're not going to poke the DB. The rest is the same. I'm not taking any advantage of the added, modified or deleted lists at the moment. I don't know if it could be worth to do it in the future or not. For sure, it would add more complexity because we would need to get the internal storage of CalendarManager in sync. Maybe later when it will use KCalendarCore storage directly.
@pvuorela, it's still a bit WIP and I haven't tested it for real on device yet. But you may already give some feedback on design if you have time to think about it.
> [nemo-qml-plugin-calendar] Don't reload from DB when not needed.

- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendarworker.cpp
- src/calendarworker.h
mKCal is internally providing cache of loaded ranges
and recurring events since version 0.6.2. There is no
need anymore to optimise this in calendarworker.
@pvuorela, this is a follow-up of sailfishos/mkcal#19, but it requires a version bump in mkcal/CMakeLists.txt, to honour the pkgconfig(mkcal-qt5) >= 0.6.2.
> [nemo-qml-plugin-calendar] Let mKCal optimise loading.

- src/calendarevent.cpp
- src/calendarmanager.cpp
- src/calendarmanager.h
- src/calendarutils.cpp
- src/calendarutils.h
- src/calendarworker.cpp
- src/calendarworker.h
- tests/tst_calendarevent/tst_calendarevent.cpp
The two commits from #30 that looks already good to go in.
I agree that the event->incidence commit in not very useful by itself since it would prepare to load todos and journals but this will not happen without moving to KCalendarCore storage in the manager. The same for the one replacing CalendarData::EmailContact with its KCalendarCore equivalent.
Besides, about your point that you tried to avoid KCalendarCore structures from the UI thread, I may add that they have move upstream away from `::Ptr` for many small structures, like attendees, persons… So They can now be used in the UI thread without risk and would avoid code duplication.
> Add a test on CalendarEvent modification signals and use uid/recid for sendResponse manager API.

- src/calendarworker.cpp
- src/calendarworker.h
Following the introduction of `::storageUpdated()` from #28, one can now also use the callback method on database modification to actually perform complementary changes like purging deleted local events, or send invitations / updates / cancellations.
This avoids to store events marked as deleted and then try to see if they have actually been deleted to send cancellations fr instance. We're closer to the actual changes that happened in the database.
PS : the API of the service handler is slightly overly redundant : just the storage and the event would be enough. The calendar can be deduced from the storage with `storage->calendar()` and the notebook can also be deduced from the storage and the event with `storage->notebook(storage->calendar()->notebook(event))`.
> Use storage observer to do additional action on database changes

- .gitignore
- tests/tst_calendarmanager/tst_calendarmanager.cpp
I'm not sure if this will fix the issue for good but I think this is a good improvement.
Use `QTRY_COMPARE` instead of comparing in a loop waiting a little bit at a time and then doing `QCOMPARE`. This is able to tell if there is need to wait just a little bit longer for the test to pass. Also since the earlier timeout was three seconds its now five.
That last loop was strange, it was basically a three second delay. I made it to use `QTRY_VERIFY` instead. I also changed the previous wait to use similar non-racy method of waiting.
Also use range-based loops in the test and improve .gitignore file.
> Improve waiting

- src/calendarutils.cpp
- tests/tst_calendarevent/tst_calendarevent.cpp
Fix a regression introduced in ca935edb where
an organizer is always added to the attendee list
even when empty.
> [nemo-qml-plugin-calendar] Fix empty organizer.

- src/calendarworker.cpp
In relation to sailfishos/mkcal#29 this is deprecating the use of Notebook::isDefault() and replacing it with something related to ExtendedStorage::defaultNotebook() only. @pvuorela, when you have time, thank you in advance.
> [nemo-qml-plugin-calendar] Move away from Notebook::isDefault().

- src/calendarimportmodel.cpp
- src/calendarimportmodel.h
- tests/tests.pro
- tests/tests.xml
- tests/tst_calendarimportmodel/tst_calendarimportmodel.cpp
- tests/tst_calendarimportmodel/tst_calendarimportmodel.pro
This PR is adding the possibility to drop invitations when importing then from ICS data, so such events are not seen as external invitations.
Typical use case is when one receive an event by typing an "add to calendar" link on a website and this event is set with an organizer. By keeping the organizer when importing the event, the event becomes "read-only" in the calendar application, because it is seen as an external invitation.
@pvuorela, I've taken the benefit of this minor addition to create a test for the importation model. The UI part of this PR is not ready yet though !
> [nemo-qml-plugin-calendar] Allow to discard invitation on importation.

- tools/icalconverter/main.cpp
No-op if bool parameter is true and otherwise there area lready calls to setGeoLatitude/Longitude.
@dcaliste
> [nemo-calendar] Remove deprecated use of Incidence::setHasGeo(). Fixes JB#60292

- lightweight/calendardataservice/calendardataservice.pro
- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendaragendamodel.cpp
- src/calendaragendamodel.h
- src/calendareventlistmodel.cpp
- src/calendareventlistmodel.h
- src/calendareventoccurrence.h
- src/calendareventquery.cpp
- src/calendareventquery.h
- src/calendarmanager.cpp
- src/calendarmanager.h
- src/calendarworker.cpp
- src/calendarworker.h
- src/src.pro
Create a hard dependency on Timed to get the timezone change info.
@pvuorela : this is allowing to change the timezone in the system setting on device and the calendar still displays events at the right date and time. If the event is floating, no change is done. If the event is given by UTC or in a timezone, the display time is shifted accordingly. If it requires a date change, the event is moved and agenda models are updated accordingly. Maybe you have a long standing JB id available for this ? ;-)
The `emitStorageModified()` may seem a bit overkill, but the caching mechanism in mKCal will make it much less resource intensive. The ranges won't be reloaded for instance, just the occurrences will be recomputed (which is desired). All the events by UID will be reloaded though. I may add a …
> [nemo-qml-plugin-calendar] Reset calendar on timezone change on device.

- lightweight/calendardataservice/calendardataservice.pro
- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendareventlistmodel.cpp
- src/calendareventlistmodel.h
- src/calendarmanager.cpp
- src/calendarmanager.h
- src/calendarsearchmodel.cpp
- src/calendarsearchmodel.h
- src/calendarworker.cpp
- src/calendarworker.h
- src/plugin.cpp
- src/src.pro
- tests/tests.pro
- tests/tst_calendarsearchmodel/tst_calendarsearchmodel.cpp
- tests/tst_calendarsearchmodel/tst_calendarsearchmodel.pro
Add a search function to CalendarManager. It is based on ExtendedStorage::search() method. The worker is loading all matching incidences and retrieving the corresponding instance identifiers. The later are
passed back to the manager via a new searchResults signal. While the former are sent back viw the
existing dataLoaded signal.
Also add a model listing occurrence of a search
query. This model is based on a EventListModel
where the identifiers are given as the result of
a search call.
@pvuorela, this is based on sailfishos/mkcal#49 and aims at providing a list model for search results. It is conveniently based on evntlistmodel, since such model already provide event listing from instance identifiers. I still keep this as WIP since I would like to add a loading property to the …
> [nemo-qml-plugin-calendar] Add a search model.

- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendarworker.cpp
Provides the notebook UID of the event to
purge. Not a necessity at the moment since
event UIDs are unique in the database, but
it will allow to raise the unicity constrain
between notebooks later on.
@pvuorela : it's a follow-up of sailfishos/mkcal#59.
> [nemo-qml-plugin-calendar] Specify the notebook when purging.

- src/calendareventlistmodel.cpp
- src/calendareventlistmodel.h
- src/calendareventoccurrence.cpp
- src/calendareventoccurrence.h
- src/calendarmanager.cpp
- src/calendarsearchmodel.cpp
- src/calendarsearchmodel.h
A placeholder for a possible implementation of using `getNextOccurrence()` to list recurring events in the serach results. Currently unimplemented.
It initially contains the commit adding the year section.
> Use next occurrence for recurring events in search

- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendarworker.cpp
Directly pass the notebook to the email service API instead of passing mCalendar and mStorage.
@pvuorela, this propages the changes introduced in sailfishos/mkcal#39. I'm not aware of any other repos using this service API. Please tell me if there are actually others that require an update.
> [nemo-qml-plugin-calendar] Follow mKCal API change in ServiceHandler.

- src/calendarsearchmodel.cpp
Duh, didn't see  this coming.
@Tomin1 @dcaliste
> [nemo-qml-plugin-calendar] Avoid using mkcal private header for no reason. JB#52853

- src/calendaragendamodel.cpp
- src/calendareventlistmodel.cpp
- src/calendareventquery.cpp
- src/calendarsearchmodel.cpp
If the model and the manager are both owned by
the QApplication, they may be deleted in a
random order on application quit. We should
then avoid to recreate a manager if this one
has been already deleted.
This situation is happening in the tests for
instance.
@pvuorela , I encountered this problem in the searchmodel test for instance. It created random segfault or a warning about QEventLoop lacking of a QApplication after the test complete.
> [nemo-qml-plugin-calendar] Avoid creating a manager on delete.

- lightweight/calendardataservice/calendardataservice.cpp
- lightweight/calendareventsmodel/calendareventsmodel.cpp
- lightweight/calendareventsmodel/calendareventsmodel.h
- lightweight/common/eventdata.cpp
- lightweight/common/eventdata.h
- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendaragendamodel.cpp
- src/calendarapi.cpp
- src/calendarapi.h
- src/calendardata.h
- src/calendarevent.cpp
- src/calendarevent.h
- src/calendareventlistmodel.cpp
- src/calendareventoccurrence.cpp
- src/calendareventoccurrence.h
- src/calendareventquery.cpp
- src/calendareventquery.h
- src/calendarimportevent.cpp
- src/calendarinvitationquery.cpp
- src/calendarinvitationquery.h
- src/calendarmanager.cpp
- src/calendarmanager.h
- src/calendarutils.cpp
- src/calendarutils.h
- src/calendarworker.cpp
- src/calendarworker.h
- tests/tst_calendarevent/tst_calendarevent.cpp
- tests/tst_calendarsearchmodel/tst_calendarsearchmodel.cpp
Remove the recurrenceId from the API, so uniqueId
is able to uniquely identify an event, or an exception.
This is done internally by affecting the
instanceIdentifier to Event::uniqueId.
This would allow later to add a notebook UID
information to this uniqueId and thus being
able to add multi-notebook support without
changing once again the API.
@pvuorela , this one is more to open a discussion on the evolution of the nemo-qml-plugin-calendar API, because with incidences that can share the same UID between notebooks, obviously things like Manager::eventObject(uid, recId) or CalendarApi::remove(uid, recurrenceId, startTime) are broken. I can see three ways to solve this:
1. Add a notebookUid argument to such routines, which means an API break for the public routines or additionnal required …
> Make Event::uniqueId sole identifier for events.

- rpm/nemo-qml-plugin-calendar-qt5.spec
- src/calendarimportmodel.cpp
- src/calendarimportmodel.h
- tests/tst_calendarimportmodel/tst_calendarimportmodel.cpp
When two events in different notebooks can
share the same UID, the detection of duplicates
during the importation must be done per
notebook and not globally when parsing the
ICS data.
and also:
The instanceId member of CalendarData::Event
is used to identify the event uniquely in the
manager. Any other usage of CalendarData::Event
should not set this value, since the event may
not be owned by the manager.
@pvuorela, this sadly implies to change the API of calendarimportmodel. Indeed, the duplication must be detected when selecting a destination notebook, and changing this destination should rerun the duplication check. That's why I created a new property setting the notebookuid. It's still WIP since I need to create the corresponding PR for the UI.
> [nemo-qml-plugin-calendar] Allow multi-notebook when importing. Contributes to JB#60800

- src/calendarmanager.cpp
Loading in progress should not block the views from refreshing, but just block additional call to
'loadData'. When data are loaded anyway, it will
emit a 'dataLoaded' signal that will trigger a new refresh if needed.
@pvuorela, this comes from an investigation of a strange behaviour of the calendar application of Steve Everett who I privately contacted when I see his report of [calendar not being available](https://forum.sailfishos.org/t/sorry-jolla-4-6/18839/22). I'm afraid he is suffering from several bugs, but one that is striking is (quoting his own description):
> You go into a calendar (which has many entries) and nothing is displayed. It is as though the calendar is empty. You see the horizontal line at the top of the screen flashing as for a sync. When this stops flashing after a …
> [nemo-qml-plugin-calendar] Refresh models even when loading in progress.
